version: '3.9'

services:

  # ----------------------------------------------------
  # API GATEWAY
  # ----------------------------------------------------

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "9000:8080"
    depends_on:
      - eureka-server
    restart: on-failure
    networks:
      - TP_Back
    
  # ----------------------------------------------------
  # EUREKA SERVER
  # ----------------------------------------------------

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka_server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - TP_Back

  # ----------------------------------------------------
  # SERVICIO DEPOSITOS
  # ----------------------------------------------------

  servicio-depositos:
    build:
      context: ./servicio-depositos
      dockerfile: Dockerfile
    container_name: ms_depositos
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - db_depositos
    restart: on-failure # Si la app falla, intenta reiniciarla
    networks:
      - TP_Back

  db_depositos:
    image: postgres:16
    container_name: db_depositos

    ports:
      - "5433:5432"

    volumes:
      - depositos_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_depositos
    networks:
      - TP_Back

  # ----------------------------------------------------
  # SERVICIO PERSONAS
  # ----------------------------------------------------

  servicio-personas:
    build:
      context: ./servicio-personas
      dockerfile: Dockerfile
    container_name: ms_personas
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
      - db_personas
    restart: on-failure
    networks:
      - TP_Back

  db_personas:
    image: postgres:16
    container_name: db_personas
    ports:
      - "5434:5432"
    volumes:
      - personas_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_personas
    networks:
      - TP_Back

  # ----------------------------------------------------
  # SERVICIO RUTAS
  # ----------------------------------------------------

  servicio-rutas:
    build:
      context: ./servicio-rutas
      dockerfile: Dockerfile
    container_name: ms_rutas
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
      - db_rutas
    restart: on-failure
    networks:
      - TP_Back

  db_rutas:
    image: postgres:16
    container_name: db_rutas
    ports:
      - "5435:5432"
    volumes:
      - rutas_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_rutas
    networks:
      - TP_Back

  # ----------------------------------------------------
  # SERVICIO SOLICITUDES
  # ----------------------------------------------------

  servicio-solicitudes:
    build:
      context: ./servicio-solicitudes
      dockerfile: Dockerfile
    container_name: ms_solicitudes
    ports:
      - "8083:8080"
    depends_on:
      - eureka-server
      - db_solicitudes
    restart: on-failure
    networks:
      - TP_Back

  db_solicitudes:
    image: postgres:16
    container_name: db_solicitudes
    ports:
      - "5436:5432"
    volumes:
      - solicitudes_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_solicitudes
    networks:
      - TP_Back
  
  # ----------------------------------------------------
  # SERVICIO TARIFAS
  # ----------------------------------------------------

  servicio-tarifas:
    build:
      context: ./servicio-tarifas
      dockerfile: Dockerfile
    container_name: ms_tarifas
    ports:
      - "8084:8080"
    depends_on:
      - eureka-server
      - db_tarifas
    restart: on-failure
    networks:
      - TP_Back

  db_tarifas:
    image: postgres:16
    container_name: db_tarifas
    ports:
      - "5437:5432"
    volumes:
      - tarifas_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_tarifas
    networks:
      - TP_Back

  # ----------------------------------------------------
  # KEYCLOAK
  # ----------------------------------------------------

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - TP_Back

  # ----------------------------------------------------
  # OSRM - ROUTING SERVICE (Opcional)
  # ----------------------------------------------------

  osrm:
    image: osrm/osrm-backend
    container_name: osrm_server
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed /data/argentina-latest.osrm
    restart: on-failure
    networks:
      - TP_Back
    profiles:
      - osrm

  # ----------------------------------------------------
  # KAFKA
  # ----------------------------------------------------

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - TP_Back

  # ----------------------------------------------------
  # DEFINICIÓN DE VOLÚMENES PERSISTENTES
  # ----------------------------------------------------
volumes:
  depositos_data:
  personas_data:
  rutas_data:
  solicitudes_data:
  tarifas_data:

  # ----------------------------------------------------
  # DEFINICIÓN DE REDES
  # ----------------------------------------------------
networks:
  # Red personalizada para comunicación interna de todos los microservicios y DBs
  TP_Back:
    driver: bridge
