spring.application.name=api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true 
eureka.client.fetch-registry=true

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/tp-backend

# Logging Configuration
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=TRACE
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=TRACE
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
