# === CONFIGURACIÓN DEL SERVICIO PERSONAS ===
spring.application.name=personas
server.port=8080

spring.datasource.url=jdbc:postgresql://db_personas:5432/db_personas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# =========== LOGGING CONFIG ===========
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.ar.edu.utn.frc.backend=DEBUG

# Logs de SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Archivo de logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n
