# === CONFIGURACIÓN DEL SERVICIO PERSONAS ===
spring.application.name=personas
server.port=8080

spring.datasource.url=jdbc:postgresql://db_personas:5432/db_personas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/tp-backend

# === CLIENT CREDENTIALS CONFIG ===
spring.security.oauth2.client.registration.ms-personas.provider=keycloak
spring.security.oauth2.client.registration.ms-personas.client-id=ms-personas
spring.security.oauth2.client.registration.ms-personas.client-secret=BIP4JShuUDHZmkzYdZlUcChB66JRjjWq
spring.security.oauth2.client.registration.ms-personas.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/tp-backend/protocol/openid-connect/token

# === KAFKA CONFIG ===
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =========== LOGGING CONFIG ===========
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.ar.edu.utn.frc.backend=DEBUG

# Logs de SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Archivo de logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n
